const OK = 200;
const CREATED = 201;
const DELETED = 204;
const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const NOT_ACCEPTABLE = 406;
const SERVER_ERROR = 500;

module.exports = {
    OK, DELETED, CREATED, NOT_FOUND, BAD_REQUEST, UNAUTHORIZED, SERVER_ERROR, NOT_ACCEPTABLE
}
